spec-version: 0.35.1
name: bookshelf
version: 0.1.0.0
maintainer: Head-Gardener <rashbin2019np@gmail.com>
category: Web
extra-source-files:
  - CHANGELOG.md

ghc-options: 
  - -Wall

language: GHC2021
default-extensions:
  - OverloadedStrings
  - QuasiQuotes
  - TemplateHaskell
  - TypeFamilies
  - FlexibleContexts
  - FlexibleInstances
  - DerivingStrategies
  - UndecidableInstances
  - DataKinds
  - ViewPatterns

dependencies:
  - base >= 4.12 && < 5
  - text
  - mtl
  - persistent
  - persistent-sqlite
  - time
  - monad-logger
  - resourcet

library:
  source-dirs: src
  generated-other-modules: Paths_bookshelf
  dependencies:
    - utf8-string
    - magic

executables:
  edge:
    source-dirs: app
    main: Main.hs
    generated-other-modules: Paths_bookshelf
    dependencies:
      - bookshelf
      - yesod
    ghc-options:
      - -threaded
  manager:
    source-dirs: manager
    main: Main.hs
    generated-other-modules: Paths_bookshelf
    dependencies:
      - bookshelf
      - directory
      - filepath
    ghc-options:
      - -threaded

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - QuickCheck
    build-tools: hspec-discover
